version: '3.5'

services:
  bsdpy:
    image: "testing:latest"
    ports:
      - "67:67/udp"
    environment:
      - DOCKER_BSDPY_IP=10.49.56.200
    volumes:
      - /nbi:/nbi
    entrypoint:
      - /bsdpserver.py
      - -p
      - /nbi
      - -i
      - eth0
      - -r
      - http

#  tftp:
#    image: "testing:latest"
#    volumes:
#      - /nbi:/nbi
#    ports:
#      - "69:69/udp"
#    entrypoint:
#      - /usr/sbin/in.tftpd
#      - --foreground
#      - --verbosity
#      - "10"
#      - --verbose
#      - --blocksize
#      - "1468"
#      - /nbi
    
  tftp:
    image: "testing:latest"
    volumes:
      - /nbi:/nbi
    ports:
      - "69:69/udp"
    entrypoint:
      - /usr/sbin/atftpd
      - --daemon
      - --no-fork
      - -v
      - --logfile
      - "-"
      - /nbi

  http:
    image: "testing:latest"
    ports:
      - "80:80/tcp"
    volumes:
      - /nbi:/nbi
    entrypoint:
      - /usr/sbin/nginx
      - -c
      - /etc/nginx/nginx.conf

